prompt Creating synonym for PETE_010000_DEV.PETET_PLSQL_BLOCK
create or replace synonym PETET_PLSQL_BLOCK for PETE_010000_DEV.PETET_PLSQL_BLOCK;

prompt Creating synonym for PETE_010000_DEV.PETET_EXPECTED_RESULT
create or replace synonym PETET_EXPECTED_RESULT for PETE_010000_DEV.PETET_EXPECTED_RESULT;

prompt Creating synonym for PETE_010000_DEV.PETET_INPUT_ARGUMENT
create or replace synonym PETET_INPUT_ARGUMENT for PETE_010000_DEV.PETET_INPUT_ARGUMENT;

prompt Creating synonym for PETE_010000_DEV.PETET_PLSQL_BLOCK_IN_CASE
create or replace synonym PETET_PLSQL_BLOCK_IN_CASE for PETE_010000_DEV.PETET_PLSQL_BLOCK_IN_CASE;

prompt Creating synonym for PETE_010000_DEV.PETET_PLSQL_BLOCKS_IN_CASE
create or replace synonym PETET_PLSQL_BLOCKS_IN_CASE for PETE_010000_DEV.PETET_PLSQL_BLOCKS_IN_CASE;

prompt Creating synonym for PETE_010000_DEV.PETET_TEST_CASE
create or replace synonym PETET_TEST_CASE for PETE_010000_DEV.PETET_TEST_CASE;

prompt Creating synonym for PETE_010000_DEV.PETET_TEST_CASE_IN_SUITE
create or replace synonym PETET_TEST_CASE_IN_SUITE for PETE_010000_DEV.PETET_TEST_CASE_IN_SUITE;

prompt Creating synonym for PETE_010000_DEV.PETET_TEST_CASES_IN_SUITE
create or replace synonym PETET_TEST_CASES_IN_SUITE for PETE_010000_DEV.PETET_TEST_CASES_IN_SUITE;

prompt Creating synonym for PETE_010000_DEV.PETET_TEST_SUITE
create or replace synonym PETET_TEST_SUITE for PETE_010000_DEV.PETET_TEST_SUITE;

prompt Creating synonym for PETE_010000_DEV.PETEV_PLSQL_BLOCK
create or replace synonym PETEV_PLSQL_BLOCK for PETE_010000_DEV.PETEV_PLSQL_BLOCK;

prompt Creating synonym for PETE_010000_DEV.PETEV_EXPECTED_RESULT
create or replace synonym PETEV_EXPECTED_RESULT for PETE_010000_DEV.PETEV_EXPECTED_RESULT;

prompt Creating synonym for PETE_010000_DEV.PETEV_INPUT_ARGUMENT
create or replace synonym PETEV_INPUT_ARGUMENT for PETE_010000_DEV.PETEV_INPUT_ARGUMENT;

prompt Creating synonym for PETE_010000_DEV.PETEV_PLSQL_BLOCK_IN_CASE
create or replace synonym PETEV_PLSQL_BLOCK_IN_CASE for PETE_010000_DEV.PETEV_PLSQL_BLOCK_IN_CASE;

prompt Creating synonym for PETE_010000_DEV.PETEV_TEST_CASE
create or replace synonym PETEV_TEST_CASE for PETE_010000_DEV.PETEV_TEST_CASE;

prompt Creating synonym for PETE_010000_DEV.PETEV_TEST_CASE_IN_SUITE
create or replace synonym PETEV_TEST_CASE_IN_SUITE for PETE_010000_DEV.PETEV_TEST_CASE_IN_SUITE;

prompt Creating synonym for PETE_010000_DEV.PETEV_TEST_SUITE
create or replace synonym PETEV_TEST_SUITE for PETE_010000_DEV.PETEV_TEST_SUITE;

prompt Creating synonym for PETE_010000_DEV.PETE_CONFIG
create or replace synonym PETE_CONFIG for PETE_010000_DEV.PETE_CONFIG;

prompt Creating synonym for PETE_010000_DEV.PETE_CONFIGURATION_RUNNER_ADM
create or replace synonym PETE_CONFIGURATION_RUNNER_ADM for PETE_010000_DEV.PETE_CONFIGURATION_RUNNER_ADM;

prompt Creating synonym for PETE_010000_DEV.PETE
create or replace synonym PETE for PETE_010000_DEV.PETE;
